services:
  - type: web
    name: photo-mosaic-api
    runtime: python
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt
    startCommand: bash scripts/startup.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: GITHUB_ASSETS_TOKEN
        sync: false
      - key: GITHUB_ASSETS_REPO
        value: nkspranay/mosaic-private-assets
      - key: NASA_API_KEY
        sync: false
      - key: UNSPLASH_ACCESS_KEY
        sync: false
      - key: PIXABAY_API_KEY
        sync: false
      - key: OVERRIDE_MAP
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false